import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenu, NavigationMenuList, NavigationMenuLink } from "@/components/ui/navigation-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationMenu className="fixed top-0 left-0 right-0">
          <NavigationMenuList>
            <NavigationMenuLink href="/">Home</NavigationMenuLink>
            <NavigationMenuLink href="/about">About</NavigationMenuLink>
            <NavigationMenuLink href="/contact">Contact</NavigationMenuLink>
            <NavigationMenuLink href="/blog">Blog</NavigationMenuLink>
            <NavigationMenuLink href="/shop">Shop</NavigationMenuLink>
            <NavigationMenuLink href="/login">Login</NavigationMenuLink>
            <NavigationMenuLink href="/register">Register</NavigationMenuLink>
          </NavigationMenuList>
        </NavigationMenu>
        {children}
      </body>
    </html>
  );
}
